services:
    serviceB:
        image: mockserver/mockserver:5.14.0
        command: -logLevel DEBUG -serverPort 80

    serviceA:
        image: mockserver/mockserver:5.14.0
        command: -logLevel DEBUG -erverPort 80

    eureka:
        build: eureka
        ports:
            - 8761:8761

    openssh-server:
        image: lscr.io/linuxserver/openssh-server:latest
        container_name: openssh-server
        environment:
            - DOCKER_MODS=linuxserver/mods:openssh-server-ssh-tunnel
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - PUBLIC_KEY_FILE=/ssh-keys/oporto.pub
            - SUDO_ACCESS=true
            - USER_NAME=finn
            - LOG_STDOUT=
        volumes:
            - ./config:/ssh-keys:rw
        ports:
            - 2222:2222
